swagger:
    enable: true
spring:
    datasource:
        url: jdbc:h2:mem:RealH2InUserd;DB_CLOSE_DELAY=-1;MODE=MYSQL
    h2:
        console:
            enabled: true
            path: /h2
#        url: jdbc:h2:file:./RealH2InUserd;DB_CLOSE_DELAY=-1;MODE=MYSQL
mybatis:
    configuration:
        mapUnderscoreToCamelCase: true